DROP DATABASE KMS;
CREATE DATABASE KMS;
USE KMS;

CREATE TABLE NKM_MANAGER_INFO(
	ID VARCHAR(100) PRIMARY KEY,
	PASSWORD VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100),
	NAME VARCHAR(100),
	TYPE VARCHAR(20),
	DESCRIPTION VARCHAR(4000),
	STATUS VARCHAR(20),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100)
);

CREATE TABLE NKM_MANAGER_HISTORY(
	HIST_NO INT PRIMARY KEY,
	ID VARCHAR(100),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_MANAGER_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

CREATE TABLE NKM_CLIENT_INFO(
	IP_ADDR VARCHAR(50) PRIMARY KEY,
	AUTH_TYPE VARCHAR(20),
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(4000),
	STATUS VARCHAR(20),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100)
);

CREATE TABLE NKM_CLIENT_KEY_LIST(
	KEY_ID VARCHAR(100) PRIMARY KEY,
	IP_ADDR VARCHAR(50),
	VALUE VARCHAR(100),
	STATUS VARCHAR(20),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(IP_ADDR) REFERENCES NKM_CLIENT_INFO(IP_ADDR)
);

CREATE SEQUENCE SEQ_CLIENT_KEY_ID
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 99999
	CYCLE;

CREATE TABLE NKM_CLIENT_HISTORY(
	HIST_NO INT PRIMARY KEY,
	IP_ADDR VARCHAR(50),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_CLIENT_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

CREATE TABLE NKM_HSM_GROUP_INFO(
	GROUP_ID VARCHAR(100) PRIMARY KEY,
	SLB_IP_ADDR VARCHAR(50) NOT NULL,
	SLB_PORT INT NOT NULL,
	DESCRIPTION VARCHAR(4000),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100)
);

CREATE SEQUENCE SEQ_HSM_GROUP_ID
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 99999
	CYCLE;

CREATE TABLE NKM_PARTITION_INFO(
	PARTITION_ID VARCHAR(100) NOT NULL,
	GROUP_ID VARCHAR(100) NOT NULL,
	SERVICE_ID VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(32),
	PROTECT_MODE VARCHAR(100),
	IDENT VARCHAR(64),
	DESCRIPTION VARCHAR(4000),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(GROUP_ID) REFERENCES NKM_HSM_GROUP_INFO(GROUP_ID)
);

ALTER TABLE NKM_PARTITION_INFO
ADD PRIMARY KEY (PARTITION_ID, GROUP_ID);

CREATE TABLE NKM_MNG_AUTH_INFO(
	ID VARCHAR(100) NOT NULL,
	SERVICE_ID VARCHAR(100) NOT NULL,
	CREATE_YN VARCHAR(1),
	READ_YN VARCHAR(1),
	UPDATE_YN VARCHAR(1),
	DELETE_YN VARCHAR(1),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(ID) REFERENCES NKM_MANAGER_INFO(ID)
);

ALTER TABLE NKM_MNG_AUTH_INFO
ADD PRIMARY KEY (ID, SERVICE_ID);

CREATE TABLE NKM_MNG_AUTH_HISTORY(
	HIST_NO INT PRIMARY KEY,
	ID VARCHAR(100),
	SERVICE_ID VARCHAR(100),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_MNG_AUTH_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

CREATE TABLE NKM_CLI_AUTH_INFO(
	IP_ADDR VARCHAR(50) NOT NULL,
	SERVICE_ID VARCHAR(100) NOT NULL,
	CREATE_YN VARCHAR(1),
	READ_YN VARCHAR(1),
	UPDATE_YN VARCHAR(1),
	DELETE_YN VARCHAR(1),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(IP_ADDR) REFERENCES NKM_CLIENT_INFO(IP_ADDR)
);

ALTER TABLE NKM_CLI_AUTH_INFO
ADD PRIMARY KEY (IP_ADDR, SERVICE_ID);


CREATE TABLE NKM_CLI_AUTH_HISTORY(
	HIST_NO INT PRIMARY KEY,
	IP_ADDR VARCHAR(50),
	SERVICE_ID VARCHAR(100),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_CLI_AUTH_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

CREATE TABLE NKM_HSM_INFO(
	HSM_ID VARCHAR(100) NOT NULL,
	GROUP_ID VARCHAR(100) NOT NULL,
	IP_ADDR VARCHAR(50),
	VENDOR VARCHAR(100),
	SERIAL VARCHAR(100),
	INSTALL_TYPE VARCHAR(20),
	DESCRIPTION VARCHAR(4000),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(GROUP_ID) REFERENCES NKM_HSM_GROUP_INFO(GROUP_ID)
);

ALTER TABLE NKM_HSM_INFO
ADD PRIMARY KEY (HSM_ID, GROUP_ID);

CREATE SEQUENCE SEQ_HSM_ID
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 99999999
	CYCLE;

CREATE TABLE NKM_HSM_HISTORY(
	HIST_NO INT PRIMARY KEY,
	HSM_ID VARCHAR(100),
	PARTITION_ID VARCHAR(100),
	GROUP_ID VARCHAR(100),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_HSM_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

CREATE TABLE NKM_CTLSVR_INFO(
	CTLSVR_ID VARCHAR(100) PRIMARY KEY,
	IP_ADDR VARCHAR(50) NOT NULL,
	PORT INT NOT NULL,
	DESCRIPTION VARCHAR(4000),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100)
);

CREATE TABLE NKM_HSM_CTL_LIST(
	CTLSVR_ID VARCHAR(100) NOT NULL,
	GROUP_ID VARCHAR(100) NOT NULL,
	HSM_ID VARCHAR(100) NOT NULL,
	CTL_ORDER INT,
	MODE VARCHAR(20),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(CTLSVR_ID) REFERENCES NKM_CTLSVR_INFO(CTLSVR_ID),
	FOREIGN KEY(HSM_ID, GROUP_ID) REFERENCES NKM_HSM_INFO(HSM_ID, GROUP_ID)
);

ALTER TABLE NKM_HSM_CTL_LIST
ADD PRIMARY KEY (CTLSVR_ID, GROUP_ID, HSM_ID);

CREATE TABLE NKM_CTLSVR_HISTORY(
	HIST_NO INT PRIMARY KEY,
	CTLSVR_ID VARCHAR(100),
	GROUP_ID VARCHAR(100),
	HSM_ID VARCHAR(100),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_CTLSVR_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

CREATE TABLE NKM_KEY_PROFILE_INFO(
	PROFILE_ID VARCHAR(100) PRIMARY KEY,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(4000),
	STATUS VARCHAR(20),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100)
);

CREATE SEQUENCE SEQ_KEY_PROFILE_ID
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 99999999
	CYCLE;

CREATE TABLE NKM_KEY_LIST(
	KEY_ID VARCHAR(100) NOT NULL,
	PARTITION_ID VARCHAR(100) NOT NULL,
	GROUP_ID VARCHAR(100) NOT NULL,
	PROFILE_ID VARCHAR(100) NOT NULL,
	KEY_STATUS VARCHAR(8) NOT NULL,
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(PARTITION_ID, GROUP_ID) REFERENCES NKM_PARTITION_INFO(PARTITION_ID, GROUP_ID),
	FOREIGN KEY(PROFILE_ID) REFERENCES NKM_KEY_PROFILE_INFO(PROFILE_ID)
);

ALTER TABLE NKM_KEY_LIST
ADD PRIMARY KEY (KEY_ID, PARTITION_ID, GROUP_ID);

CREATE TABLE NKM_KEY_ATTRIBUTE_INFO(
	ATTR_ID VARCHAR(100) PRIMARY KEY,
	NAME VARCHAR(100),
	TYPE VARCHAR(20),
	SIZE INT,
	DESCRIPTION VARCHAR(4000),
	STATUS VARCHAR(20),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100)
);

CREATE TABLE NKM_KEY_ATTR_LIST(
	KEY_ID VARCHAR(100) NOT NULL,
	PARTITION_ID VARCHAR(100) NOT NULL,
	GROUP_ID VARCHAR(100) NOT NULL,
	ATTR_ID VARCHAR(100) NOT NULL,
	VALUE VARCHAR(4000),
	ATTR_TYPE VARCHAR(1),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(PARTITION_ID, GROUP_ID, KEY_ID) REFERENCES NKM_KEY_LIST(PARTITION_ID, GROUP_ID, KEY_ID)
);

ALTER TABLE NKM_KEY_ATTR_LIST
ADD PRIMARY KEY (KEY_ID, PARTITION_ID, GROUP_ID, ATTR_ID);

CREATE TABLE NKM_KEY_HISTORY(
	HIST_NO INT PRIMARY KEY,
	KEY_ID VARCHAR(100),
	PARTITION_ID VARCHAR(100),
	GROUP_ID VARCHAR(100),
	ATTR_ID VARCHAR(100),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_KEY_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

CREATE TABLE NKM_KEY_PROFILE_ATTR_LIST(
	PROFILE_ID VARCHAR(100) NOT NULL,
	ATTR_ID VARCHAR(100) NOT NULL,
	ATTR_DEFAULT VARCHAR(4000),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL,
	UPT_DTTM DATETIME,
	UPT_USER VARCHAR(100),
	FOREIGN KEY(PROFILE_ID) REFERENCES NKM_KEY_PROFILE_INFO(PROFILE_ID),
	FOREIGN KEY(ATTR_ID) REFERENCES NKM_KEY_ATTRIBUTE_INFO(ATTR_ID)
);

ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST
ADD PRIMARY KEY (PROFILE_ID, ATTR_ID);

CREATE TABLE NKM_KEY_PROFILE_HISTORY(
	HIST_NO INT PRIMARY KEY,
	PROFILE_ID VARCHAR(100),
	ATTR_ID VARCHAR(100),
	TYPE VARCHAR(20),
	PARAM VARCHAR(4000),
	HMAC VARCHAR(48),
	REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	REG_USER VARCHAR(100) NOT NULL
);

CREATE SEQUENCE SEQ_KEY_PROFILE_HIST_NO
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999999999
	CYCLE;

ALTER TABLE NKM_MANAGER_INFO COMMENT = '관리자 정보 테이블';
ALTER TABLE NKM_MANAGER_INFO CHANGE ID ID VARCHAR(100) NOT NULL COMMENT '관리자 아이디';
ALTER TABLE NKM_MANAGER_INFO CHANGE PASSWORD PASSWORD VARCHAR(100) NOT NULL COMMENT '해시된 패스워드';
ALTER TABLE NKM_MANAGER_INFO CHANGE EMAIL EMAIL VARCHAR(100) COMMENT '2-Factor 인증용 이메일 주소';
ALTER TABLE NKM_MANAGER_INFO CHANGE NAME NAME VARCHAR(100) COMMENT '관리자 이름';
ALTER TABLE NKM_MANAGER_INFO CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리자 유형';
ALTER TABLE NKM_MANAGER_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_MANAGER_INFO CHANGE STATUS STATUS VARCHAR(20) COMMENT '상태코드';
ALTER TABLE NKM_MANAGER_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_MANAGER_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_MANAGER_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_MANAGER_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_MANAGER_HISTORY COMMENT = '관리자 정보 관리 이력 테이블';
ALTER TABLE NKM_MANAGER_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT '관리자 관리 이력번호';
ALTER TABLE NKM_MANAGER_HISTORY CHANGE ID ID VARCHAR(100) COMMENT '관리자 아이디';
ALTER TABLE NKM_MANAGER_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_MANAGER_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_MANAGER_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_MANAGER_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_MANAGER_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

ALTER TABLE NKM_CLIENT_INFO COMMENT = '클라이언트 정보 테이블';
ALTER TABLE NKM_CLIENT_INFO CHANGE IP_ADDR IP_ADDR VARCHAR(50) NOT NULL COMMENT '클라이언트 IP주소';
ALTER TABLE NKM_CLIENT_INFO CHANGE AUTH_TYPE AUTH_TYPE VARCHAR(20) COMMENT '클라이언트 인증 타입';
ALTER TABLE NKM_CLIENT_INFO CHANGE NAME NAME VARCHAR(100) COMMENT '클라이언트 이름';
ALTER TABLE NKM_CLIENT_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_CLIENT_INFO CHANGE STATUS STATUS VARCHAR(20) COMMENT '상태코드';
ALTER TABLE NKM_CLIENT_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_CLIENT_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_CLIENT_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_CLIENT_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_CLIENT_HISTORY COMMENT = '클라이언트 정보 관리 이력 테이블';
ALTER TABLE NKM_CLIENT_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT '클라이언트 관리 이력번호';
ALTER TABLE NKM_CLIENT_HISTORY CHANGE IP_ADDR IP_ADDR VARCHAR(50) COMMENT '클라이언트 IP주소';
ALTER TABLE NKM_CLIENT_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_CLIENT_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_CLIENT_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_CLIENT_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_CLIENT_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

ALTER TABLE NKM_CLIENT_KEY_LIST COMMENT = '클라이언트 키 리스트 테이블';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE KEY_ID KEY_ID VARCHAR(100) COMMENT '키 ID';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE IP_ADDR IP_ADDR VARCHAR(50) COMMENT '클라이언트 IP주소';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE VALUE VALUE VARCHAR(100) COMMENT '키 값';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE STATUS STATUS VARCHAR(20) COMMENT '상태코드';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_CLIENT_KEY_LIST CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_CTLSVR_INFO COMMENT = '제어서버 정보 테이블';
ALTER TABLE NKM_CTLSVR_INFO CHANGE CTLSVR_ID CTLSVR_ID VARCHAR(100) NOT NULL COMMENT 'HSM 제어서버 ID';
ALTER TABLE NKM_CTLSVR_INFO CHANGE IP_ADDR IP_ADDR VARCHAR(50) NOT NULL COMMENT 'HSM 제어서버 IP주소';
ALTER TABLE NKM_CTLSVR_INFO CHANGE PORT PORT INT NOT NULL COMMENT 'HSM 제어서버 포트';
ALTER TABLE NKM_CTLSVR_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_CTLSVR_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_CTLSVR_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_CTLSVR_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_CTLSVR_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_CTLSVR_HISTORY COMMENT = '제어서버 정보 관리 이력 테이블';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT 'HSM 제어서버 관리 이력번호';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE CTLSVR_ID CTLSVR_ID VARCHAR(100) COMMENT 'HSM 제어서버 ID';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE GROUP_ID GROUP_ID VARCHAR(100) COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE HSM_ID HSM_ID VARCHAR(100) COMMENT 'HSM ID';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_CTLSVR_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

ALTER TABLE NKM_HSM_INFO COMMENT = 'HSM 정보 테이블';
ALTER TABLE NKM_HSM_INFO CHANGE HSM_ID HSM_ID VARCHAR(100) NOT NULL COMMENT 'HSM ID';
ALTER TABLE NKM_HSM_INFO CHANGE GROUP_ID GROUP_ID VARCHAR(100) NOT NULL COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_HSM_INFO CHANGE IP_ADDR IP_ADDR VARCHAR(50) COMMENT 'HSM IP주소';
ALTER TABLE NKM_HSM_INFO CHANGE VENDOR VENDOR VARCHAR(100) COMMENT 'HSM 제조사';
ALTER TABLE NKM_HSM_INFO CHANGE SERIAL SERIAL VARCHAR(100) COMMENT '시리얼 번호';
ALTER TABLE NKM_HSM_INFO CHANGE INSTALL_TYPE INSTALL_TYPE VARCHAR(20) COMMENT 'HSM 설치유형';
ALTER TABLE NKM_HSM_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_HSM_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_HSM_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_HSM_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_HSM_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_HSM_GROUP_INFO COMMENT = 'HSM 그룹 정보 테이블';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE GROUP_ID GROUP_ID VARCHAR(100) NOT NULL COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE SLB_IP_ADDR SLB_IP_ADDR VARCHAR(50) NOT NULL COMMENT 'SLB IP주소';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE SLB_PORT SLB_PORT INT NOT NULL COMMENT 'SLB 포트';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_HSM_GROUP_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_PARTITION_INFO COMMENT = '파티션 정보 테이블';
ALTER TABLE NKM_PARTITION_INFO CHANGE PARTITION_ID PARTITION_ID VARCHAR(100) NOT NULL COMMENT 'HSM 파티션 ID';
ALTER TABLE NKM_PARTITION_INFO CHANGE GROUP_ID GROUP_ID VARCHAR(100) NOT NULL COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_PARTITION_INFO CHANGE SERVICE_ID SERVICE_ID VARCHAR(100) NOT NULL UNIQUE COMMENT '서비스 구분 ID';
ALTER TABLE NKM_PARTITION_INFO CHANGE PASSWORD PASSWORD VARCHAR(32) COMMENT 'HSM 파티션 패스워드';
ALTER TABLE NKM_PARTITION_INFO CHANGE PROTECT_MODE PROTECT_MODE VARCHAR(100) COMMENT 'HSM 보호모드';
ALTER TABLE NKM_PARTITION_INFO CHANGE IDENT IDENT VARCHAR(64) COMMENT 'HSM 파티션 IDENT 값';
ALTER TABLE NKM_PARTITION_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_PARTITION_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_PARTITION_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_PARTITION_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_PARTITION_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_HSM_HISTORY COMMENT = '제어서버 정보 관리 이력 테이블';
ALTER TABLE NKM_HSM_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT 'HSM 관리 이력번호';
ALTER TABLE NKM_HSM_HISTORY CHANGE HSM_ID HSM_ID VARCHAR(100) COMMENT 'HSM ID';
ALTER TABLE NKM_HSM_HISTORY CHANGE PARTITION_ID PARTITION_ID VARCHAR(100) COMMENT 'HSM 파티션 ID';
ALTER TABLE NKM_HSM_HISTORY CHANGE GROUP_ID GROUP_ID VARCHAR(100) COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_HSM_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_HSM_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_HSM_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_HSM_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_HSM_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

ALTER TABLE NKM_MNG_AUTH_INFO COMMENT = '관리자별 파티션 권한 테이블';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE ID ID VARCHAR(100) NOT NULL COMMENT '관리자 아이디';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE SERVICE_ID SERVICE_ID VARCHAR(100) NOT NULL COMMENT '서비스 구분 ID';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE CREATE_YN CREATE_YN VARCHAR(1) COMMENT '키 생성 허용 여부';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE READ_YN READ_YN VARCHAR(1) COMMENT '키 조회 허용 여부';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE UPDATE_YN UPDATE_YN VARCHAR(1) COMMENT '키 정보 업데이트 허용 여부';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE DELETE_YN DELETE_YN VARCHAR(1) COMMENT '키 삭제 허용 여부';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_MNG_AUTH_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_MNG_AUTH_HISTORY COMMENT = '관리자별 파티션 권한 관리 이력 테이블';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT '관리자 파티션 관리 이력번호';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE ID ID VARCHAR(100) COMMENT '관리자 ID';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE SERVICE_ID SERVICE_ID VARCHAR(100) COMMENT '서비스 구분 ID';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_MNG_AUTH_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

ALTER TABLE NKM_CLI_AUTH_INFO COMMENT = '클라이언트별 파티션 권한 테이블';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE IP_ADDR IP_ADDR VARCHAR(50) NOT NULL COMMENT '클라이언트 IP주소';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE SERVICE_ID SERVICE_ID VARCHAR(100) NOT NULL COMMENT '서비스 구분 ID';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE CREATE_YN CREATE_YN VARCHAR(1) COMMENT '키 생성 허용 여부';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE READ_YN READ_YN VARCHAR(1) COMMENT '키 조회 허용 여부';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE UPDATE_YN UPDATE_YN VARCHAR(1) COMMENT '키 정보 업데이트 허용 여부';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE DELETE_YN DELETE_YN VARCHAR(1) COMMENT '키 삭제 허용 여부';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_CLI_AUTH_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_CLI_AUTH_HISTORY COMMENT = '클라이언트별 파티션 권한 관리 이력 테이블';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT '클라이언트 파티션 관리 이력번호';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE IP_ADDR IP_ADDR VARCHAR(50) COMMENT '클라이언트 IP 주소';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE SERVICE_ID SERVICE_ID VARCHAR(100) COMMENT '서비스 구분 ID';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_CLI_AUTH_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

ALTER TABLE NKM_HSM_CTL_LIST COMMENT = 'HSM 제어 리스트 테이블';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE CTLSVR_ID CTLSVR_ID VARCHAR(100) NOT NULL COMMENT 'HSM 제어서버 ID';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE HSM_ID HSM_ID VARCHAR(100) NOT NULL COMMENT 'HSM ID';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE CTL_ORDER CTL_ORDER INT COMMENT 'HSM 제어 우선순위';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE MODE MODE VARCHAR(20) COMMENT 'HSM 제어 모드';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_HSM_CTL_LIST CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_KEY_PROFILE_INFO COMMENT = '키 프로파일 정보 테이블';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE PROFILE_ID PROFILE_ID VARCHAR(100) NOT NULL COMMENT '키 프로파일 ID';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE NAME NAME VARCHAR(100) COMMENT '키 프로파일명';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE STATUS STATUS VARCHAR(20) COMMENT '키 프로파일 상태';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_KEY_PROFILE_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_KEY_ATTRIBUTE_INFO COMMENT = '키 속성 정보 테이블';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE ATTR_ID ATTR_ID VARCHAR(100) NOT NULL COMMENT '키 속성 ID';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE NAME NAME VARCHAR(100) COMMENT '키 속성 이름';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE TYPE TYPE VARCHAR(20) COMMENT '키 속성 자료형';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE SIZE SIZE INT COMMENT '키 속성 자료형 크기';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE DESCRIPTION DESCRIPTION VARCHAR(4000) COMMENT '설명';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE STATUS STATUS VARCHAR(20) COMMENT '키 프로파일 상태';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_KEY_ATTRIBUTE_INFO CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST COMMENT = '키 프로파일 속성 리스트 테이블';
ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST CHANGE PROFILE_ID PROFILE_ID VARCHAR(100) NOT NULL COMMENT '키 프로파일 ID';
ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST CHANGE ATTR_ID ATTR_ID VARCHAR(100) NOT NULL COMMENT '키 속성 ID';
ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST CHANGE ATTR_DEFAULT ATTR_DEFAULT VARCHAR(4000) COMMENT '기본값';
ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_KEY_PROFILE_ATTR_LIST CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_KEY_PROFILE_HISTORY COMMENT = '키 프로파일 관리 이력 테이블';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT 'HSM 관리 이력번호';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE PROFILE_ID PROFILE_ID VARCHAR(100) COMMENT '키 프로파일 ID';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE ATTR_ID ATTR_ID VARCHAR(100) COMMENT '키 속성 ID';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_KEY_PROFILE_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

ALTER TABLE NKM_KEY_LIST COMMENT = '키 리스트 테이블';
ALTER TABLE NKM_KEY_LIST CHANGE KEY_ID KEY_ID VARCHAR(100) NOT NULL COMMENT '키 ID';
ALTER TABLE NKM_KEY_LIST CHANGE PARTITION_ID PARTITION_ID VARCHAR(100) NOT NULL COMMENT 'HSM 파티션 ID';
ALTER TABLE NKM_KEY_LIST CHANGE GROUP_ID GROUP_ID VARCHAR(100) NOT NULL COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_KEY_LIST CHANGE PROFILE_ID PROFILE_ID VARCHAR(100) NOT NULL COMMENT '키 프로파일 ID';
ALTER TABLE NKM_KEY_LIST CHANGE KEY_STATUS KEY_STATUS VARCHAR(8) NOT NULL COMMENT '키 상태';
ALTER TABLE NKM_KEY_LIST CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_KEY_LIST CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_KEY_LIST CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_KEY_LIST CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_KEY_ATTR_LIST COMMENT = '키 속성 리스트 테이블';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE KEY_ID KEY_ID VARCHAR(100) NOT NULL COMMENT '키 ID';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE PARTITION_ID PARTITION_ID VARCHAR(100) NOT NULL COMMENT 'HSM 파티션 ID';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE GROUP_ID GROUP_ID VARCHAR(100) NOT NULL COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE ATTR_ID ATTR_ID VARCHAR(100) NOT NULL COMMENT '키 속성 ID';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE VALUE VALUE VARCHAR(4000) COMMENT '키 속성값';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE ATTR_TYPE ATTR_TYPE VARCHAR(1) COMMENT '키 속성 타입';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE UPT_DTTM UPT_DTTM DATETIME COMMENT '수정 일시';
ALTER TABLE NKM_KEY_ATTR_LIST CHANGE UPT_USER UPT_USER VARCHAR(100) COMMENT '수정 계정';

ALTER TABLE NKM_KEY_HISTORY COMMENT = '키 관리 이력 테이블';
ALTER TABLE NKM_KEY_HISTORY CHANGE HIST_NO HIST_NO INT NOT NULL COMMENT 'HSM 관리 이력번호';
ALTER TABLE NKM_KEY_HISTORY CHANGE KEY_ID KEY_ID VARCHAR(100) COMMENT '키 ID';
ALTER TABLE NKM_KEY_HISTORY CHANGE PARTITION_ID PARTITION_ID VARCHAR(100) COMMENT 'HSM 파티션 ID';
ALTER TABLE NKM_KEY_HISTORY CHANGE GROUP_ID GROUP_ID VARCHAR(100) COMMENT 'HSM 그룹 ID';
ALTER TABLE NKM_KEY_HISTORY CHANGE ATTR_ID ATTR_ID VARCHAR(100) COMMENT '키 속성 ID';
ALTER TABLE NKM_KEY_HISTORY CHANGE TYPE TYPE VARCHAR(20) COMMENT '관리 코드';
ALTER TABLE NKM_KEY_HISTORY CHANGE PARAM PARAM VARCHAR(4000) COMMENT '추가 파라미터';
ALTER TABLE NKM_KEY_HISTORY CHANGE HMAC HMAC VARCHAR(48) COMMENT '위변조 체크 코드';
ALTER TABLE NKM_KEY_HISTORY CHANGE REG_DTTM REG_DTTM DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '등록 일시';
ALTER TABLE NKM_KEY_HISTORY CHANGE REG_USER REG_USER VARCHAR(100) NOT NULL COMMENT '등록 계정';

INSERT INTO `NKM_KEY_ATTRIBUTE_INFO` (`ATTR_ID`, `NAME`, `TYPE`, `SIZE`, `DESCRIPTION`, `STATUS`, `REG_DTTM`, `REG_USER`, `UPT_DTTM`, `UPT_USER`) VALUES
	('canExportKey', '키 내보내기 가능여부', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('canImportKey', '외부에서 생성된 키 주입 가능 여부', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('cryptographicAlgorithm', '암호 알고리즘', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('curve', 'EC 알고리즘에서 사용되는 Recommended Curve', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('keyActivationType', '키 활성화 유형', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('keyLabel', '키 라벨', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('keyLength', '키의 길이', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('keyLifetime', '키의 수명', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('keyObjectType', '키 객체 유형', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('keyPairId', '키 쌍 ID', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('keyUsageMask', '키의 용도', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL),
	('publicExponent', 'Public Exponent', NULL, NULL, NULL, NULL, DEFAULT, 'ADMIN', NULL, NULL);
;